### DISCUSSION TITLE
Authelia - custom implementation over lldap?

### DISCUSSION THREAD

**Discussion by parasiteoflife** [lldap/lldap#1063] [Q&A]
In the Authelia example you used `implementation: 'custom'` but I see authelia has `lldap` as an option, should we not use that?

**Comment by nitnelave** [comment]
Our fame is catching up to us, it seems! Authelia was one of the first integrations to be worked out, and there definitely wasn't an LLDAP option then.
Can you give it a try and update the configuration guide? That would be super helpful.

**Comment by ottobaer** [comment]
I just tried to set this up. 

It works as expected and I can do user/group lookups in authelia. 



```

  ldap:
    address: 'ldap://127.0.0.1:3890'
    implementation: 'lldap'
    timeout: '5 seconds'
    start_tls: false
    base_dn: 'dc=some,dc=thing,dc=es'
    user: 'uid=admin,ou=people,dc=some,dc=thing,dc=es'
    password: 'somepass'
```

I'm sure you can leave out start_tls and timeout too.
