### DISCUSSION TITLE
Error when enabling LDAPS - Unknown environment variable: LLDAP_LDAPS_OPTIONS (SSL certificate?)

### DISCUSSION THREAD

**Discussion by Alumni1506** [lldap/lldap#1068] [Q&A] [answered]
Docker folder structure
uppercase=directory lowercase=file

```
DOCKERDATA
|__SECRETS
|  |
|  |__LLDAP
|       certfile.crt
|       keyfile.key
|
|__LLDAP
     lldap.yaml
     lldap.env
     DATA
```

YAML file
```
---
services:
  lldap:
    container_name: lldap
    hostname: lldap
    image: nitnelave/lldap:latest
    #expose:
    ports:
      - 3890:3890
      - 6360:6360
      - 17170:17170  # Web UI
    env_file:
      - lldap.env
    volumes:
      - ./data:/data
    restart: unless-stopped
```

ENV File (relevant section shown)

```
# If using LDAPS, set enabled true and configure cert and key path
LLDAP_LDAPS_OPTIONS__ENABLED=true
LLDAP_LDAPS_OPTIONS__CERT_FILE=$SECRETSDIR/lldap/certfile.crt
LLDAP_LDAPS_OPTIONS__KEY_FILE=$SECRETSDIR/lldap/keyfile.key
```

With the setup above i get the following error

```
> Setup permissions..
> Starting lldap..

Loading configuration from /data/lldap_config.toml
WARNING: Unknown environment variable: LLDAP_LDAPS_OPTIONS
2024-12-31T18:40:31.162197883+00:00  INFO     set_up_server [ 2.93ms | 100.00% ]
2024-12-31T18:40:31.162214942+00:00  INFO     ┝━ ｉ [info]: Starting LLDAP version 0.5.1-alpha
2024-12-31T18:40:31.166180643+00:00  INFO     ┕━ ｉ [info]: Starting the LDAP server on port 3890
Error: while binding the LDAP server

Caused by:
    0: while setting up the SSL certificate
    1: No such file or directory (os error 2)
```

What am i doing wrong?

**Comment by nitnelave** [comment, marked as answer]
Are you mounting the secrets in the container? Open a shell in the container, and explore the file structure. I think you're missing a mount.

A couple of nits: use lldap/lldap (same, just the new name). You probably don't want to expose your LDAP ports to the internet, unless you're accessing them from outside the machine. And you probably have a stray "LLDAP_LDAPS_OPTIONS" environment variable that doesn't do anything

**Reply by Alumni1506** [reply]
Not mounting the secrets folder was the issue.
I created a secrets folder in the lldap directory and placed only the keyfile and cert in the folder. This folder is then mounted into the container. 

So my configuration is as follows.

Docker folder structure
uppercase=directory lowercase=file

```
DOCKERDATA
|__SECRETS
|  |
|  |__LLDAP (not mounted)
|       JWT_SECRET_FILE
|       LDAP_USER_PASS
|
|__LLDAP
|     lldap.yaml
|     lldap.env
|___DATA
|___SECRETS (mounted)
        certfile.crt
        keyfile.key
```

YAML file
```
---
services:
  lldap:
    container_name: lldap
    hostname: lldap
    image: lldap/lldap:latest
    expose:
      - 3890     # LDAP
      - 6360     # LDAPS
    ports:
      - 17170:17170  # Web UI
    env_file:
      - lldap.env
    volumes:
      - ./data:/data
      - ./secrets:/secrets
    restart: unless-stopped
```

ENV File (relevant section shown)

```
# Secrets: lldap reads them from the specified files.
# This way, the secrets are not part of any process' environment.
LLDAP_JWT_SECRET=$SECRETSDIR/lldap/JWT_SECRET_FILE
LLDAP_LDAP_USER_PASS=$SECRETSDIR/lldap/LDAP_USER_PASS

# If using LDAPS, set enabled true and configure cert and key path
LLDAP_LDAPS_OPTIONS__ENABLED=true
LLDAP_LDAPS_OPTIONS__CERT_FILE=/secrets/certfile.crt
LLDAP_LDAPS_OPTIONS__KEY_FILE=/secrets/keyfile.key
```

I no longer get the error and the container looks to be working. Is the new setup above correct?
Do i need to also mount JWT_SECRET_FILE and LDAP_USER_PASS into the container via the newly created secrets folder?
