### DISCUSSION TITLE
Is there a count limit for tokens?

### DISCUSSION THREAD

**Discussion by Pierre-Lannoy** [lldap/lldap#1191] [Q&A]
Hello all!

I'm currently working on an cross-integration with [Pilos](https://github.com/THM-Health/PILOS/) and WHMCS.
I've made many tests with GraphQL and each query/mutation was starting with a call to `auth/login/simple` to get a new fresh token (and, so I was not using refresh token). It is not the final behavior, il plan to cache token and refresh token to do things right but, that was my tests ;)
After many tests (so after generating many new tokens) I've experiment a 401 to obtain new token (with same method, always same user, password and admin group).

As nothing has changed in my config, I wonder if I've reached some kind of limit in token generation… Do you think it's the case? If so, do you have some hint to "reset" the token list?

Thank you for your help,
Pierre

**Comment by Pierre-Lannoy** [comment]
In case you're wondering, it is fully reproducible like that (with a user admin that can open a session on web frontend):

```
curl --location 'http://127.0.0.1:17170/auth/simple/login' \
--header 'Content-Type: application/json' \
--data-raw '{
    "username": "uid=<redacted>,ou=people,dc=<redacted>,dc=eu",
    "password": "<redacted>"
}'

`Authentication error for user "uid=<redacted>,ou=people,dc=<redacted>,dc=eu"`
```

**Comment by nitnelave** [comment]
There is no token limit or any kind of rate limiting implemented in LLDAP.

The only thing is that we store the active sessions so it grows the DB (there's a cleanup job for outdated tokens), but I doubt you're hitting the limits of the DB

Are you maybe getting to LLDAP through a proxy that has rate limiting?

**Comment by Pierre-Lannoy** [comment]
Yes, I do, but my example with curl is on local machine (so, without proxy).
What is really strange is the behavior is for all admins, not only the one which I used to do my tests…

**Reply by nitnelave** [reply]
Could I get the verbose logs? With LLDAP_VERBOSE=true in the env

**Reply by Pierre-Lannoy** [reply]
Yes, here it is…
```
lldap-1    | 2025-06-13T09:18:06.966359001+00:00  DEBUG    HTTP request [ 1.75ms | 15.36% / 100.00% ] method: "POST" | uri: "/auth/simple/login"
lldap-1    | 2025-06-13T09:18:06.966609804+00:00  DEBUG    ┝━ simple_login [ 1.48ms | 1.32% / 84.64% ]
lldap-1    | 2025-06-13T09:18:06.966626185+00:00  DEBUG    │  ┕━ bind [ 1.45ms | 3.10% / 83.32% ]
lldap-1    | 2025-06-13T09:18:06.966637847+00:00  DEBUG    │     ┝━ get_password_file_for_user [ 1.40ms | 80.22% ] user_id: "uid=<redacted>,ou=people,dc=<redacted>,dc=eu"
lldap-1    | 2025-06-13T09:18:06.968918897+00:00  DEBUG    │     ┝━ 🐛 [debug]: User "uid=<redacted>,ou=people,dc=<redacted>,dc=eu" doesn't exist or has no password
lldap-1    | 2025-06-13T09:18:06.968923746+00:00  ERROR    │     ┕━ 🚨 [error]:  | error: Authentication error for user "uid=<redacted>,ou=people,dc=<redacted>,dc=eu"
lldap-1    | 2025-06-13T09:18:06.968948894+00:00  DEBUG    ┕━ 🐛 [debug]:  | status_code: 401
```

**Reply by nitnelave** [reply]
"user doesn't exist or has no password"

Can you try resetting the password maybe?

**Reply by Pierre-Lannoy** [reply]
Just done it… No luck :/

For the records, I'm using LLDAP with docker with the following `docker-compose.yml` file:

```
  ldapdb:
    image: "mariadb:11"
    environment:
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
    volumes:
      - "./ldapdb:/var/lib/mysql"
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      retries: 12
      timeout: 5s
  lldap:
    image: lldap/lldap:stable
    env_file: .env
    ports:
      - "127.0.0.1:3890:3890"
      - "127.0.0.1:17170:17170"
    volumes:
      - "./lldap/data:/data"
    depends_on:
      ldapdb:
        condition: service_healthy
    environment:
      - UID=1000
      - GID=1000
      - TZ=Europe/Paris
      - LLDAP_JWT_SECRET=${LDAP_JWT_SECRET}
      - LLDAP_KEY_SEED=${LDAP_KEY_SEED}
      - LLDAP_LDAP_BASE_DN=${LDAP_LDAP_BASE_DN}
      - LLDAP_LDAP_USER_PASS=${LDAP_LDAP_USER_PASS}
      - LLDAP_DATABASE_URL=mysql://${DB_USERNAME}:${DB_PASSWORD}@ldapdb:${DB_PORT}/${DB_DATABASE}
      - LLDAP_SMTP_OPTIONS__ENABLE_PASSWORD_RESET=true
      - LLDAP_SMTP_OPTIONS__SERVER=${MAIL_HOST}
      - LLDAP_SMTP_OPTIONS__PORT=${MAIL_PORT}
      - LLDAP_SMTP_OPTIONS__SMTP_ENCRYPTION=TLS
      - LLDAP_SMTP_OPTIONS__USER=${MAIL_USERNAME}
      - LLDAP_SMTP_OPTIONS__PASSWORD=${MAIL_PASSWORD}
      - LLDAP_SMTP_OPTIONS__FROM=${MAIL_FROM_NAME} <${MAIL_FROM_ADDRESS}>
```
