### DISCUSSION TITLE
Authelia integration

### DISCUSSION THREAD

**Discussion by djjudas21** [lldap/lldap#888] [General]
I'm new to both lldap and Authelia but I'm running into this error when Authelia starts up:

```
time="2024-03-30T22:28:35Z" level=info msg="Authelia v4.37.5 is starting"
time="2024-03-30T22:28:35Z" level=info msg="Log severity set to info"
time="2024-03-30T22:28:35Z" level=info msg="Storage schema is being checked for updates"
time="2024-03-30T22:28:35Z" level=info msg="Storage schema is already up to date"
time="2024-03-30T22:28:35Z" level=error msg="Failure running the user provider startup check: bind failed with error: LDAP Result Code 64 \"Naming Violation\": Not a subtree of the base tree" stack="github.com/authelia/authelia/v4/internal/commands/root.go:287 doStartupChecks\ngithub.com/authelia/authelia/v4/internal/commands/root.go:87  cmdRootRun\ngithub.com/spf13/cobra@v1.6.1/command.go:920                  (*Command).execute\ngithub.com/spf13/cobra@v1.6.1/command.go:1044                 (*Command).ExecuteC\ngithub.com/spf13/cobra@v1.6.1/command.go:968                  (*Command).Execute\ngithub.com/authelia/authelia/v4/cmd/authelia/main.go:10       main\nruntime/proc.go:250                                           main\nruntime/asm_amd64.s:1594                                      goexit"
```

Relevant environment variables from my lldap config:

```
LLDAP_BASE_DN:                   dc=gazeley,dc=uk
```

Relevant config from Authelia, adapted from the [example config](https://github.com/lldap/lldap/blob/main/example_configs/authelia_config.yml):

```yaml
  authentication_backend:
    ldap:
      enabled: true
      implementation: custom
      url: ldap://lldap-ldap.auth.svc.cluster.local:3890
      timeout: 5s
      start_tls: false
      base_dn: dc=gazeley,dc=uk
      username_attribute: uid
      additional_users_dn: ou=people
      users_filter: "(&({username_attribute}={input})(objectClass=person))"
      additional_groups_dn: ou=groups
      groups_filter: "(member={dn})"
      group_name_attribute: cn
      mail_attribute: mail
      display_name_attribute: displayName
      user: uid=authelia,ou=people,dc=gazeley,dc=uk
      password: ************
```

I've double checked that the `authelia` user exists and is a member of the `lldap_password_manager` group.

If I am understanding this properly, the `LDAP Result Code 64 \"Naming Violation\": Not a subtree of the base tree"` error is being returned by lldap, not Authelia? Seems like the error implies that `uid=authelia,ou=people,dc=gazeley,dc=uk` is not under `dc=gazeley,dc=uk`.

Any clues on how to track this down? Thanks

**Comment by nitnelave** [comment]
Hey! I think authelia doesn't report the entire error. If you look at the LLDAP logs (potentially after setting verbose to true), you should have more info about the error: what was sent vs what was expected.

**Comment by djjudas21** [comment]
I set verbose to true and captured this:

```
2024-03-31T18:37:54.408209906+00:00  INFO     LDAP session [ 157µs | 45.06% / 100.00% ]
2024-03-31T18:37:54.408255657+00:00  INFO     ┕━ LDAP request [ 86.3µs | 49.21% / 54.94% ]
2024-03-31T18:37:54.408275150+00:00  DEBUG       ┝━ 🐛 [debug]:  | msg: LdapMsg { msgid: 1, op: BindRequest(LdapBindRequest { dn: "uid=authelia,ou=people,dc=gazeley,dc=uk", cred: LdapBindCred::Simple }), ctrl: [] }
2024-03-31T18:37:54.408277781+00:00  DEBUG       ┝━ do_bind [ 9.01µs | 5.73% ] dn: uid=authelia,ou=people,dc=gazeley,dc=uk
2024-03-31T18:37:54.408300851+00:00  DEBUG       ┕━ 🐛 [debug]:  | response: BindResponse(LdapBindResponse { res: LdapResult { code: NamingViolation, matcheddn: "", message: "Not a subtree of the base tree", referral: [] }, saslcreds: None })
```

**Reply by nitnelave** [reply]
At the beginning of the verbose logs, you get a dump of your config as seen by lldap. Can you look for the base DN there? It should match what you request (so dc=gazeley,dc=uk)

**Comment by djjudas21** [comment]
You called it. I am setting these values but it looks like my helm chart contains a bug which is causing it to silently skip a bunch of config options which come after that bug. So `ldap_base_bn` actually reverts to the default value, and my SMTP config is not set properly either. This is on me to fix, but thanks for the pointer.

Looks like it's something to do with the parsing of this [this line](https://github.com/djjudas21/charts/blob/main/charts/lldap/templates/deployment.yaml#L68) causing all the following lines to get skipped. But right now the weather is nice so I'm taking my daughter to the skate park! I'll have a look at the code this evening :slightly_smiling_face: 

```
Configuration: Configuration {
    ldap_host: "0.0.0.0",
    ldap_port: 3890,
    http_host: "0.0.0.0",
    http_port: 17170,
    jwt_secret: ***SECRET***,
    ldap_base_dn: "dc=example,dc=com",
    ldap_user_dn: UserId(
        "admin",
    ),
    ldap_user_email: "",
    ldap_user_pass: ***SECRET***,
    database_url: "mysql://lldap:lldap@lldap-mariadb/lldap",
    ignored_user_attributes: [],
    ignored_group_attributes: [],
    verbose: true,
    key_file: "/data/private_key",
    key_seed: Some(
        ***SECRET***,
    ),
    smtp_options: MailOptions {
        enable_password_reset: false,
        from: None,
        reply_to: None,
        server: "localhost",
        port: 587,
        user: "",
        password: ***SECRET***,
        smtp_encryption: Tls,
        tls_required: None,
    },
    ldaps_options: LdapsOptions {
        enabled: false,
        port: 6360,
        cert_file: "/data/cert.pem",
        key_file: "/data/key.pem",
    },
    http_url: Url {
        scheme: "https",
        cannot_be_a_base: false,
        username: "",
        password: None,
        host: Some(
            Domain(
                "ldap.gazeley.uk",
            ),
        ),
        port: None,
        path: "/",
        query: None,
        fragment: None,
WARNING: A key_seed was given, we will ignore the server_key and generate one from the seed!
    },
    server_setup: None,
}
```

**Comment by nitnelave** [comment]
That looks like unescaped double quotes!

I'm glad you found the issue ;)

**Comment by djjudas21** [comment]
Hmm, it's not that simple. I have now fixed the helm chart so it renders the config properly. My container env vars are as follows:

```
  - env:
    - name: uid
      value: "1000"
    - name: gid
      value: "1000"
    - name: TZ
      value: Europe/London
    - name: LLDAP_HTTP_URL
      value: https://ldap.gazeley.uk/
    - name: LLDAP_LDAP_PORT
      value: "3890"
    - name: LLDAP_HTTP_PORT
      value: "17170"
    - name: LLDAP_JWT_SECRET
      valueFrom:
        secretKeyRef:
          key: jwtSecret
          name: lldap-credentials
    - name: LLDAP_LDAP_USER_PASS
      valueFrom:
        secretKeyRef:
          key: ldapUserPass
          name: lldap-credentials
    - name: LLDAP_DATABASE_URL
      value: mysql://lldap:lldap@lldap-mariadb/lldap
    - name: LLDAP_BASE_DN
      value: dc=gazeley,dc=uk
    - name: LLDAP_LDAP_USER_DN
      value: admin
    - name: LLDAP_VERBOSE
      value: "true"
    - name: LLDAP_KEY_SEED
      value: 5bf837cc3a5cd97bce18b5cb4c73eef8
    - name: LLDAP_LDAPS_OPTIONS__ENABLED
      value: "false"
    - name: LLDAP_LDAPS_OPTIONS__CERT_FILE
      value: /data/cert.pem
    - name: LLDAP_LDAPS_OPTIONS__KEY_FILE
      value: /data/key.pem
```

But the container startup shows:

```
> Setup permissions..
> Starting lldap..

Loading configuration from /data/lldap_config.toml
Configuration: Configuration {
    ldap_host: "0.0.0.0",
    ldap_port: 3890,
    http_host: "0.0.0.0",
    http_port: 17170,
    jwt_secret: ***SECRET***,
    ldap_base_dn: "dc=example,dc=com",
    ldap_user_dn: UserId(
        "admin",
    ),
    ldap_user_email: "",
    ldap_user_pass: ***SECRET***,
    database_url: "mysql://lldap:lldap@lldap-mariadb/lldap",
    ignored_user_attributes: [],
    ignored_group_attributes: [],
    verbose: true,
    key_file: "/data/private_key",
    key_seed: Some(
        ***SECRET***,
    ),
    smtp_options: MailOptions {
        enable_password_reset: false,
        from: None,
        reply_to: None,
        server: "localhost",
        port: 587,
        user: "",
        password: ***SECRET***,
        smtp_encryption: Tls,
        tls_required: None,
    },
    ldaps_options: LdapsOptions {
        enabled: false,
        port: 6360,
        cert_file: "/data/cert.pem",
        key_file: "/data/key.pem",
    },
    http_url: Url {
        scheme: "https",
        cannot_be_a_base: false,
        username: "",
        password: None,
        host: Some(
            Domain(
                "ldap.gazeley.uk",
            ),
        ),
        port: None,
        path: "/",
        query: None,
WARNING: A key_seed was given, we will ignore the server_key and generate one from the seed!
        fragment: None,
    },
    server_setup: None,
}
```

So it looks like the lldap container is not correctly reading the environment variables and is still relying on defaults from a config file. Can this be disabled? Thanks
