### DISCUSSION TITLE
Authelia feat-ldap-pool build

### DISCUSSION THREAD

**Discussion by thielj** [lldap/lldap#902] [General]
Hi,

on a low powered machine, LLDAP had a hard time serving Authelia due to constantly needing to authenticate the "bind user". This seems to have disappeared with a new feature. To build and test it, do something like this:

```bash
git clone https://github.com/authelia/authelia.git
cd authelia
git switch feat-ldap-pool 
docker build -f Dockerfile.dev -t authelia:feat-ldap-pool .
```

Then switch to the `authelia:feat-ldap-pool` image and add this to Authelia's configuration:

```yaml
authentication_backend:
  ldap:
    pooling:
      enable: true  # Use pooling.
      count: 4  # Pool count/max connections.
      retries: 3  # Number of retries within the timeout period.
      timeout: 10s  # Length of time to wait for the pool to have a connection available.
```

If that works well for you, leave some feedback here: https://github.com/authelia/authelia/discussions/7192
