### ISSUE TITLE
example of Kimai is incorrect

### ISSUE THREAD

**Issue by juntong20XX** [lldap/lldap#1142]
**Checklist**
- [x] Check if there is already an [example config](https://github.com/lldap/lldap/tree/main/example_configs) for it.
- [x] Try to figure out the configuration values for the new service yourself.
  - You can use other example configs for inspiration.
  - If you're having trouble, you can ask on [Discord](https://discord.gg/h5PEdRMNyP) or create an issue.
  - If you succeed, make sure to contribute an example configuration, or a configuration guide.
- If you hit a block because of an unimplemented feature, create an issue.

**Description of the service**

[Kimal](https://www.kimai.org/documentation/ldap.html) supports automatically assigning their roles in Kimal based on the group of ldap users. However, in the [example file](https://github.com/lldap/lldap/blob/main/example_configs/kimai.yaml), the `usernameAttribute` value is incorrect, causing the function to be unusable.

**What you've tried**
```yaml
<skip ...>
    role:
      baseDn: ou=groups, dc=example, dc=com
      filter: (&(objectClass=groupOfUniqueNames))
      usernameAttribute: cn
      nameAttribute: cn
      userDnAttribute: member
<skip...>
```

**What's not working**
The role of users cannot be updated!

**How I fixed it**:
```yaml
<skip ...>
    role:
      baseDn: ou=groups, dc=example, dc=com
      filter: (&(objectClass=groupOfUniqueNames))
      usernameAttribute: uid
      nameAttribute: cn
      userDnAttribute: member
<skip...>
```
the value of `usernameAttribute` should be `uid`, not `cn`.

Kimai version: `2.31.0`
lldap image version: `stable`
