### ISSUE TITLE
[BUG] Unable to start 0.6.1 with mariadb as db backend.

### ISSUE THREAD

**Issue by Pierre-Lannoy** [lldap/lldap#1184]
Hello!

**Describe the bug**
Unable to start 0.6.1 with mariadb as db backend.

**To Reproduce**
1. Create a `docker-compose.yml` (see content below)
2. execute `docker compose up -d`
3. try to access to web ui `curl http://127.0.0.1:17170` => Couldn't connect to server

**Expected behavior**
It should work.

**Logs**
`docker compose logs` gives:
```console
lldap-1    | > Setup permissions..
lldap-1    | > Starting lldap..
lldap-1    |
lldap-1    | Loading configuration from /data/lldap_config.toml
lldap-1    | WARNING: A key_seed was given, we will ignore the key_file and generate one from the seed! Set key_file to an empty string in the config to silence this message.
lldap-1    | Error: Connection Error: pool timed out while waiting for an open connection
lldap-1    |
lldap-1    | Caused by:
lldap-1    |     0: pool timed out while waiting for an open connection
lldap-1    |     1: pool timed out while waiting for an open connection
lldap-1    | 2025-06-03T16:52:20.947737523+00:00  INFO     set_up_server [ 3.28ms | 100.00% ]
lldap-1    | 2025-06-03T16:52:20.947768982+00:00  INFO     ┕━ ｉ [info]: Starting LLDAP version 0.6.1
```

**Additional context**
When switching to sqlite, it's working

`docker-compose.yml` content:

```yml
   ldapdb:
    image: "mariadb:11"
    environment:
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
    volumes:
      - "./ldapdb:/var/lib/mysql"
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 5s
      retries: 12
      timeout: 5s
  lldap:
    image: lldap/lldap:stable
    env_file: .env
    ports:
      - "127.0.0.1:3890:3890"
      - "127.0.0.1:17170:17170"
    volumes:
      - "./lldap/data:/data"
    depends_on:
      ldapdb:
        condition: service_healthy
    environment:
      - UID=1000
      - GID=1000
      - TZ=Europe/Paris
      - LLDAP_JWT_SECRET=${LDAP_JWT_SECRET}
      - LLDAP_KEY_SEED=${LDAP_KEY_SEED}
      - LLDAP_LDAP_BASE_DN=${LDAP_LDAP_BASE_DN}
      - LLDAP_LDAP_USER_PASS=${LDAP_LDAP_USER_PASS}
      - LLDAP_DATABASE_URL=mysql://${DB_USERNAME}:${DB_PASSWORD}@127.0.0.1:${DB_PORT}/${DB_DATABASE}
      - LLDAP_SMTP_OPTIONS__ENABLE_PASSWORD_RESET=true
      - LLDAP_SMTP_OPTIONS__SERVER=${MAIL_HOST}
      - LLDAP_SMTP_OPTIONS__PORT=${MAIL_PORT}
      - LLDAP_SMTP_OPTIONS__SMTP_ENCRYPTION=TLS
      - LLDAP_SMTP_OPTIONS__USER=${MAIL_USERNAME}
      - LLDAP_SMTP_OPTIONS__PASSWORD=${MAIL_PASSWORD}
      - LLDAP_SMTP_OPTIONS__FROM=${MAIL_FROM_NAME} <${MAIL_FROM_ADDRESS}>
   ```
