### ISSUE TITLE
Ability to use ldap over SSL/TLS

### ISSUE THREAD

**Issue by mitchins** [lldap/lldap#460]
I scoured the documents and issues but couldn't see any information about SSL/TLS.

Is there either support for it, a work around or helper proxy or any planned support for it?

I know in most cases it's probably running inside a docker overlay network that's secure, but I'm just considering opening it up to other machines on the network.

Thanks, I love the software, it's so slick and easy to use.

**Comment by nitnelave** [comment]
I think you're looking for LDAPS :) See the config for the relevant options.

**Comment by mitchins** [comment]
Thanks, most of that's on me... I didn't know to search for LDAPS as I am just a casual user of the LDAP, however I do search for "certificate" or "ssl".
In an effort to help anyone else I have raised
https://github.com/nitnelave/lldap/pull/461

If it seems like overkill feel free to closeit.

**Comment by nuka-cola** [comment]
Would it be too much to ask to integrate into LLDAP the ability to use Let'sEncrypt/Acme to auto generate and manage the certificates from the webui?  Bonus points if it can utilize the DNS API challenges instead of exposing ports to the internet.  It could even just be a nice front-end to the Dehydrate script (if that can be embedded without challenge).

**Comment by nitnelave** [comment]
This is better handled outside LLDAP: with a reverse proxy like traefik, you can configure it to highjack the request to .well-known/ to reply to the HTTP challenge, and then you can mount the certificates in the LLDAP container.

**Comment by nitnelave** [comment]
Example traefik config:

traefik.yml:
```yaml

acme:
  storage: "/etc/traefik/acme/acme.json"
  entryPoint: "https"
  onHostRule: true
  onDemand: true
  httpChallenge:
    entryPoint: "http"

certificatesResolvers:
  letsEncrypt:
    acme:
      email: your@email.com
      storage: /etc/traefik/acme/acme.json
      httpChallenge:
        # used during the challenge
        entryPoint: http
```

dynamic/letsencrypt.yml:
```yaml
http:
  routers:
    letsencrypt:
      rule: "PathPrefix(`/.well-known/acme-challenge/`)"
      entrypoints: https
      tls: true
      priority: 1000
      service: acme-http@internal
```
