### ISSUE TITLE
Also provide alternate image registry to `ghcr`?

### ISSUE THREAD

**Issue by budimanjojo** [lldap/lldap#527]
Hello! Thanks for this amazing project!

Dockerhub's rate limits (100/6hours pull actions) is frustrating to deal with when you have a lot of containers. It would be great to also host the images on `ghcr` or maybe `quay.io`. The implementation should also be pretty easy looking at the current workflow that push the images. I believe it's as simple as adding these lines to this file: https://github.com/lldap/lldap/blob/main/.github/workflows/docker-build-static.yml

Below this: https://github.com/lldap/lldap/blob/86b2b5148d107883b1dc0fd004c7ca2a8c8d653e/.github/workflows/docker-build-static.yml#L469-L474 add:

```
      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
```

And in every line like this: https://github.com/lldap/lldap/blob/86b2b5148d107883b1dc0fd004c7ca2a8c8d653e/.github/workflows/docker-build-static.yml#L487

change them to something like this:
```
          tags: |
            nitnelave/lldap:latest, nitnelave/lldap:latest-alpine
            ghcr.io/lldap/lldap:latest, ghcr.io/lldap/lldap:latest-alpine
```

I can do a PR if you don't have time to do this. Thanks before.
