### ISSUE TITLE
[docker-mailserver] Hello need help for Dovecot Configuration

### ISSUE THREAD

**Issue by ddiawara** [lldap/lldap#642]
I want to configure for auth  with docker mailserver

```
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: mail.example.com
    domainname: example.com
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS)
      - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
    volumes:
      - mailserver-data:/var/mail
      - mailserver-state:/var/mail-state
      - mailserver-config:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
    restart: always
    stop_grace_period: 1m
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0
    environment:
      - ENABLE_FAIL2BAN=1
      # >>> Postfix LDAP Integration
      - ACCOUNT_PROVISIONER=LDAP
      - LDAP_SERVER_HOST=lldap:3890 
      - LDAP_SEARCH_BASE=ou=people,dc=example,dc=com
      - LDAP_BIND_DN=cn=admin,ou=people,dc=example,dc=com
      - LDAP_BIND_PW=NicePassword
      - SPOOF_PROTECTION=1
      # <<< Postfix LDAP Integration

      # >>> Dovecot LDAP Integration
      - DOVECOT_BASE=ou=people,dc=example,dc=com
      - DOVECOT_DN=cn=admin,ou=people,dc=example,dc=com
      - DOVECOT_DNPASS=NicePassword
      - DOVECOT_AUTH_BIND=yes
      - DOVECOT_USER_ATTRS=homeDirectory=home,uidNumber=uid,gidNumber=gid
      # <<< Dovecot LDAP Integration

```

![image](https://github.com/lldap/lldap/assets/62718811/55933e13-accc-416c-ba3b-1c1ac154ff7a)

Thanks

**Comment by ddiawara** [comment]
![image](https://github.com/lldap/lldap/assets/62718811/099045c8-bb77-45ba-ab91-6a8ce668bd9c)

`2023-08-06T01:44:57.314159005+00:00  INFO     ┕━ LDAP request [ 54.2µs | 0.01% ]
2023-08-06T01:44:57.316919296Z 2023-08-06T01:44:57.316825880+00:00  ERROR    🚨 [error]: [LDAP] Service Error: while handling incoming messages: while receiving LDAP op: ldapmsg invalid
2023-08-06T01:44:57.672359421Z 2023-08-06T01:44:57.317568296+00:00  INFO     LDAP session [ 346ms | 0.10% / 100.00% ]
2023-08-06T01:44:57.672633671Z 2023-08-06T01:44:57.317707838+00:00  INFO     ┝━ LDAP request [ 346ms | 99.90% ]
2023-08-06T01:44:57.672855880Z 2023-08-06T01:44:57.671927880+00:00  ERROR    ┝━ 🚨 [error]: Invalid tagclass
2023-08-06T01:44:57.673038463Z 2023-08-06T01:44:57.671959088+00:00  INFO     ┕━ LDAP request [ 3.21µs | 0.00% ]
2023-08-06T01:44:57.673278671Z 2023-08-06T01:44:57.672269421+00:00  ERROR    🚨 [error]: [LDAP] Service Error: while handling incoming messages: while receiving LDAP op: ldapmsg invalid
2023-08-06T01:44:58.019408672Z 2023-08-06T01:44:57.674604546+00:00  INFO     LDAP session [ 340ms | 0.09% / 100.00% ]
2023-08-06T01:44:58.019838672Z 2023-08-06T01:44:57.674710213+00:00  INFO     ┝━ LDAP request [ 340ms | 99.91% ]
2023-08-06T01:44:58.020217797Z 2023-08-06T01:44:58.018958963+00:00  ERROR    ┝━ 🚨 [error]: Invalid tagclass
2023-08-06T01:44:58.020546297Z 2023-08-06T01:44:58.018988838+00:00  INFO     ┕━ LDAP request [ 3.67µs | 0.00% ]
2023-08-06T01:44:58.020892005Z 2023-08-06T01:44:58.019323755+00:00  ERROR    🚨 [error]: [LDAP] Service Error: while handling incoming messages: while receiving LDAP op: ldapmsg invalid
2023-08-06T01:45:07.307337634Z 2023-08-06T01:45:07.295695343+00:00  INFO     LDAP session [ 2.43ms | 32.75% / 100.00% ]`

**Comment by nitnelave** [comment]
I haven't used dovecot, so this is just a guess from a cursory reading of
the documentation.

You need to specify "uris" with ldap://my_server:3890 or
ldaps://my_server:6360

You need to do an authentication bind, not a password bind, so
auth_bind=yes.
And then for the template:
auth_bind_userdn = uid=%u,ou=people,dc=...

Can you try with that?

**Comment by ddiawara** [comment]
This is what a try to do LLDAP + docker-Mailserver + ROUNDCUBE (don't esitate if you have a best combo will appreciate it)
Login successfull on roundcube ui, greats thing but can't send mail and retrive mail

```
  lldap:
    image: nitnelave/lldap:stable
    ports:
      - "3890:3890"
      - "17170:17170"
    volumes:
      - "lldap_data:/data"
    environment:
      - TZ=Etc/UTC
      - LLDAP_JWT_SECRET=94721b2ada4bf1ba6462f5eb341ff08372392dbf76
      - LLDAP_LDAP_USER_PASS=admin123
      - LLDAP_LDAP_BASE_DN=dc=example,dc=com
      - LLDAP_DATABASE_URL=postgres://lldap:lldap@postgres/lldapdb
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: mailserver # mail #mail.example.com
    domainname: example.com
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS)
      - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
    volumes:
      - /var/mail
      - /var/mail-state
      - /tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
    restart: always
    stop_grace_period: 1m
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0
    environment:
      #- ONE_DIR=1 # 'ONE_DIR=1' but no volume was mounted to '/var/mail-state'
      - DMS_DEBUG=0
      - ENABLE_FAIL2BAN=1
      # >>> Postfix LDAP Integration
      - ACCOUNT_PROVISIONER=LDAP
      - LDAP_SERVER_HOST=lldap:3890
      - LDAP_SEARCH_BASE=dc=example,dc=com
      - LDAP_BIND_DN=cn=admin,ou=people,dc=example,dc=com
      - LDAP_BIND_PW=admin123
      - SPOOF_PROTECTION=1
      # <<< Postfix LDAP Integration

      # >>> Dovecot LDAP Integration
      - DOVECOT_BASE=dc=example,dc=com
      - DOVECOT_DN=cn=admin,ou=people,dc=example,dc=com
      - DOVECOT_DNPASS=admin123
      - DOVECOT_AUTH_BIND=yes
      - DOVECOT_USER_FILTER=(&(objectClass=inetOrgPerson)(mail=%u))
      - DOVECOT_USER_ATTRS==uid=5000,=gid=5000,=home=/var/mail/%Ln,=mail=maildir:~/Maildir
      # <<< Dovecot LDAP Integration

      # >>> SASL LDAP Authentication
      - ENABLE_SASLAUTHD=1
      - SASLAUTHD_MECHANISMS=ldap
      - SASLAUTHD_LDAP_SERVER=lldap:3890
      - SASLAUTHD_LDAP_BIND_DN=cn=admin,ou=people,dc=example,dc=com
      - SASLAUTHD_LDAP_PASSWORD=admin123
      - SASLAUTHD_LDAP_SEARCH_BASE=dc=example,dc=com
      - SASLAUTHD_LDAP_FILTER=(cn=%s)
      # <<< SASL LDAP Authentication
  roundcubemail:
    image: roundcube/roundcubemail:latest
    container_name: roundcubemail
    restart: always
    volumes:
      - roundcube_data:/var/www/html
    ports:
      - "9002:80"
    environment:
      - ROUNDCUBEMAIL_SKIN=elastic
      - ROUNDCUBEMAIL_DEFAULT_HOST=mailserver
      - ROUNDCUBEMAIL_SMTP_SERVER=mailserver
      #
      - ROUNDCUBEMAIL_DB_TYPE=pgsql
      - ROUNDCUBEMAIL_DB_HOST=postgres # same as pgsql container name
      - ROUNDCUBEMAIL_DB_NAME=roundcubedb # same as pgsql POSTGRES_DB env name
      - ROUNDCUBEMAIL_DB_USER=roundcube # same as pgsql POSTGRES_USER env name
      - ROUNDCUBEMAIL_DB_PASSWORD=roundcube # same as pgsql POSTGRES_PASSWORD env name
```

![image](https://github.com/lldap/lldap/assets/62718811/47bd921a-6326-4b2a-808d-3fce881aa9d8)
---
MailServer logs

![image](https://github.com/lldap/lldap/assets/62718811/f563deda-e1e5-4b28-935d-22aae70172c6)
---
Roundcube logs

![image](https://github.com/lldap/lldap/assets/62718811/b4591282-5979-4216-a3cc-87f500eccb50)

Lldap logs 
![image](https://github.com/lldap/lldap/assets/62718811/25df24ef-4569-4c08-8d17-7f239733e67b)
