### ISSUE TITLE
[FEATURE REQUEST] Accept .pem input for CERT_FILE and KEY_FILE

### ISSUE THREAD

**Issue by crltc** [lldap/lldap#740]
**Motivation**
Certbot and other tools generate .pem file types but LLDAP expects .crt and .key file types.

**Describe the solution you'd like**
Accept .pem format for CERT_FILE and KEY_FILE

**Describe alternatives you've considered**
A simple renaming of the file type works but it is an additional step, especially when it comes to renewal.
cp privkey.pem privkey.key
cp fullchain.pem fullchain.crt

**Additional context**

Environment Variables:
      - LLDAP_LDAPS_OPTIONS__ENABLED=true
      - LLDAP_LDAPS_OPTIONS__CERT_FILE=/certs/fullchain.pem
      - LLDAP_LDAPS_OPTIONS__KEY_FILE=/certs/privkey.pem

Error Logs:
Loading configuration from /data/lldap_config.toml
2023-11-18T22:58:52.896096119+00:00  INFO     set_up_server [ 4.10ms | 100.00% ]
2023-11-18T22:58:52.896128426+00:00  INFO     ┝━ ｉ [info]: Starting LLDAP version 0.5.1-alpha
2023-11-18T22:58:52.929989375+00:00  INFO     ┕━ ｉ [info]: Starting the LDAP server on port 3890
2023-11-18T22:58:52.930173015+00:00  ERROR    🚨 [error]: Could not bring up the servers: while binding the LDAP server: while setting up the SSL certificate: No such file or directory (os error 2)
2023-11-18T22:58:52.930450496+00:00  INFO     ｉ [info]: End.

**Comment by crltc** [comment]
Apologies for the late reply but indeed what I posted in my original post is indeed what I am still observing. I tried it again and renamed the file to privkey.pem and fullchain.pem and the container fails with the same error. I rename to .key and .crt and it works again. Permissions are unchanged.

**Comment by nitnelave** [comment]
How do you configure it? How do you set the environment variables, or the values in the config file?

**Comment by crltc** [comment]
Full environment variables and volume mounts below. For testing permissions were set to 777.

```
---
version: '3.8'
services:
  lldap:
    image: nitnelave/lldap
    environment:
      - LLDAP_JWT_SECRET_FILE=redacted
      - LLDAP_LDAP_USER_PASS_FILE=redacted
      - LLDAP_LDAP_BASE_DN=redacted
      - LLDAP_DATABASE_URL_FILE=redacted
      - LLDAP_LDAPS_OPTIONS__ENABLED=true
      - LLDAP_LDAPS_OPTIONS__CERT_FILE=/certs/fullchain.pem
      - LLDAP_LDAPS_OPTIONS__KEY_FILE=/certs/privkey.pem
      - LLDAP_SMTP_OPTIONS__ENABLE_PASSWORD_RESET=true
      - LLDAP_SMTP_OPTIONS__SERVER=redacted
      - LLDAP_SMTP_OPTIONS__PORT=587
      - LLDAP_SMTP_OPTIONS__SMTP_ENCRYPTION=NONE
      - LLDAP_SMTP_OPTIONS__FROM=redacted
      - LLDAP_SMTP_OPTIONS__REPLY_TO=redacted
    volumes:
      - /lldap/data:/data
      - /lldap/certbot/data/live/redacted:/certs
```
