### ISSUE TITLE
[BUG] It's possible to add a user several times to the same group by graphql api

### ISSUE THREAD

**Issue by Sad-Soul-Eater** [lldap/lldap#745]
**Describe the bug**
It's possible to add a user several times to the same group by graphql api

**To Reproduce**
You can use [bootstrap.sh](https://github.com/lldap/lldap/blob/main/example_configs/bootstrap/bootstrap.md) to quickly deploy lldap instance in the needed state:

1. Download [bootstrap.sh](https://github.com/lldap/lldap/blob/main/example_configs/bootstrap/bootstrap.sh)
2. Create a `docker-compose.yaml` with the next content:

<details><summary> docker-compose.yaml</font></summary> 

```yaml
version: "3"

services:
  lldap:
    image: lldap/lldap:v0.5.0
    volumes:
      - ./bootstrap.sh:/bootstrap/bootstrap.sh
      - ./user.json:/bootstrap/user-configs/user.json
      - ./groups.json:/bootstrap/group-configs/groups.json
    ports:
      - "3890:3890" # For LDAP
      - "17170:17170" # For the web front-end
    environment:
      # envs required for lldap
      - LLDAP_LDAP_USER_EMAIL=admin@hiso.icu
      - LLDAP_LDAP_USER_PASS=changeme
      - LLDAP_LDAP_BASE_DN=dc=example,dc=com

      # envs required for bootstrap.sh
      - LLDAP_URL=http://localhost:17170
      - LLDAP_ADMIN_USERNAME=admin
      - LLDAP_ADMIN_PASSWORD=changeme
      - USER_CONFIGS_DIR=/bootstrap/user-configs
      - GROUP_CONFIGS_DIR=/bootstrap/group-configs
      - DO_CLEANUP=true
```

</details>

3. Create a `groups.json` file with the next content:

<details><summary> groups.json</font></summary> 

```json
{"name": "group-1"}
{"name": "group-2"}
```

</details>

4. Create a `user.json` file with the next content:

<details><summary> user.json</font></summary> 

```json
{
  "id": "username",
  "email": "username@example.com",
  "groups": [
    "group-1",
    "group-1",
    "group-1",
    "group-1",
    "group-2"
  ]
}
```

</details>

5. Run the following commands: 

```bash
docker compose up -d
docker compose exec lldap /bootstrap/bootstrap.sh
docker compose exec lldap apk add openldap-clients
docker compose exec lldap ldapsearch -LLL -H ldap://localhost:3890 -D uid=admin,ou=people,dc=example,dc=com -w 'changeme' -b "ou=people,dc=example,dc=com" "uid=username" memberof
```

**Expected behavior**
LLDAP doesn't duplicate `memberof` fields

**Logs**
![image](https://github.com/lldap/lldap/assets/20245745/bf01d4e0-79ff-43b2-8445-9faba822d542)

**Additional context**
I faced this issue when tried to integrate lldap with sftpgo with the option `primary-group-prefix` - to automatically add a user to the group, but because I run the bootstrap script regularly it adds users to the same groups every run, and because of this sftpgo failed to add users because expects that `primary-group-prefix` filter will match only one group.
