### ISSUE TITLE
[FEATURE REQUEST] Build `rootless` container image

### ISSUE THREAD

**Issue by onedr0p** [lldap/lldap#755]
**Motivation**

LLDAP cannot not run as nonroot with strict security constraints because it uses gosu and chowns data on start. As a tool that is built for security, best practices should be followed and gosu should be removed in favor of the supported method provided by the Docker runtime.

https://github.com/lldap/lldap/blob/70d85524db4d7070f1fda499702bbbd3ec2dd8b5/docker-entrypoint.sh#L24-L26

The error I get is when I set `readOnlyRootFilesystem` to `true` in Kubernetes `securityContext`: 

```
k logs -n security lldap-6bf866cc88-lnqtv
Defaulted container "main" out of: main, init-db (init)
> Setup permissions..
chown: /app: Read-only file system
```

**Describe the solution you'd like**

Remove gosu and support the official method of using the `user` option in Docker Compose:

> user
> Optional User and Group ID you want to run the container as. lldap will run using this UID:GID and any files it creates in your /config volume will also be owned by this user and group. The default for this, if not specified, is 1000:1000.

```yaml
networks:
  lldap:
    name: lldap
    external: true

services:
  recyclarr:
    image: ghcr.io/lldap/lldap
    container_name: lldap
    user: 1000:1000
    networks: [lldap]
    volumes:
      - ./lldap_data:/data
    environment:
      - TZ=America/Santiago
```
