### ISSUE TITLE
Need Help. Invalid Login for Web Interface

### ISSUE THREAD

**Issue by vincenciusgeraldo** [lldap/lldap#759]
**Describe the bug**
I'm sorry to ask this type of question again since there are so many similar issues before but i just can't seems to get it working. I just setup LLDAP on my server using Docker and can't seems to login through interface even though I have been using the correct username and password.

Here's my docker-compose.yml
```yml
lldap:
    image: lldap/lldap:stable
    container_name: lldap
    ports:
      # For LDAP
      - "3890:3890"
      # For LDAPS (LDAP Over SSL), enable port if LLDAP_LDAPS_OPTIONS__ENABLED set true, look env below
      #- "6360:6360"
      # For the web front-end
      - "17170:17170"
    volumes:
      - ./LLDAP/data:/data
    environment:
      UID: 0
      GID: 0
      TZ: Asia/Jakarta
```

here's my  lldap_config.toml
```toml
ldap_user_dn="admin"
ldap_user_pass="123456789"
```

**Expected behavior**
I should be able to login using the interface

**Logs**

![image](https://github.com/lldap/lldap/assets/17944555/299fda20-21e6-4ca5-adec-649536945955)
![image](https://github.com/lldap/lldap/assets/17944555/bcdc5e5a-5cfa-4e28-94f5-6119aff5644e)

**Additional context**
I have restart the server and remove the container to make sure that config is updated properly but still not working :disappointed:

**Comment by nitnelave** [comment]
Welcome! Sorry that you can't log in, let's try to fix that.

First things first, the config: It's recommended to start by copying the [lldap_config.docker_template.toml](https://github.com/lldap/lldap/blob/main/lldap_config.docker_template.toml) in the repository as a starting point: you'll have all the values, as well as the documentation for every parameter. In particular, it seems that you don't have the `key_file` or `key_seed` configured (the recommended one is `key_seed`). As a result, the server's private key (used to encrypt the passwords) will be regenerated every time on startup, and written to a file in `/app` (next to the `lldap` binary), which is not persisted. So as soon as you restart, every password is wrong. Same goes for the database, by the way: it will be deleted on every restart with your current configuration.

So, start by copying the template and adjust it from there. If you still have trouble, set `verbose = true` in the config, and paste (no screenshot) the entire log (including the config dump at the top) after trying to log in. You can put the logs between triple backticks:
````
```
all the logs
```
````

**Comment by vincenciusgeraldo** [comment]
Hi, thank you for the fast reply. I'm actually already using the docker cofig and just omitted the other configs.
Here's my full config:
```toml
## Default configuration for Docker.
## All the values can be overridden through environment variables, prefixed
## with "LLDAP_". For instance, "ldap_port" can be overridden with the
## "LLDAP_LDAP_PORT" variable.

## Tune the logging to be more verbose by setting this to be true.
## You can set it with the LLDAP_VERBOSE environment variable.
verbose=true

## The host address that the LDAP server will be bound to.
## To enable IPv6 support, simply switch "ldap_host" to "::":
## To only allow connections from localhost (if you want to restrict to local self-hosted services),
## change it to "127.0.0.1" ("::1" in case of IPv6)".
#ldap_host = "0.0.0.0"

## The port on which to have the LDAP server.
#ldap_port = 3890

## The host address that the HTTP server will be bound to.
## To enable IPv6 support, simply switch "http_host" to "::".
## To only allow connections from localhost (if you want to restrict to local self-hosted services),
## change it to "127.0.0.1" ("::1" in case of IPv6)".
#http_host = "0.0.0.0"

## The port on which to have the HTTP server, for user login and
## administration.
#http_port = 17170

## The public URL of the server, for password reset links.
#http_url = "http://localhost"

## Random secret for JWT signature.
## This secret should be random, and should be shared with application
## servers that need to consume the JWTs.
## Changing this secret will invalidate all user sessions and require
## them to re-login.
## You should probably set it through the LLDAP_JWT_SECRET environment
## variable from a secret ".env" file.
## This can also be set from a file's contents by specifying the file path
## in the LLDAP_JWT_SECRET_FILE environment variable
## You can generate it with (on linux):
## LC_ALL=C tr -dc 'A-Za-z0-9!#%&'\''()*+,-./:;<=>?@[\]^_{|}~' </dev/urandom | head -c 32; echo ''
jwt_secret = "<insecure_secret>"

## Base DN for LDAP.
## This is usually your domain name, and is used as a
## namespace for your users. The choice is arbitrary, but will be needed
## to configure the LDAP integration with other services.
## The sample value is for "example.com", but you can extend it with as
## many "dc" as you want, and you don't actually need to own the domain
## name.
ldap_base_dn = "dc=example,dc=com"

## Admin username.
## For the LDAP interface, a value of "admin" here will create the LDAP
## user "cn=admin,ou=people,dc=example,dc=com" (with the base DN above).
## For the administration interface, this is the username.
ldap_user_dn="admin"

## Admin email.
## Email for the admin account. It is only used when initially creating
## the admin user, and can safely be omitted.
ldap_user_email = "<email>@gmail.com"

## Admin password.
## Password for the admin account, both for the LDAP bind and for the
## administration interface. It is only used when initially creating
## the admin user.
## It should be minimum 8 characters long.
## You can set it with the LLDAP_LDAP_USER_PASS environment variable.
## This can also be set from a file's contents by specifying the file path
## in the LLDAP_LDAP_USER_PASS_FILE environment variable
## Note: you can create another admin user for user administration, this
## is just the default one.
ldap_user_pass="123456789"

## Database URL.
## This encodes the type of database (SQlite, MySQL, or PostgreSQL)
## , the path, the user, password, and sometimes the mode (when
## relevant).
## Note: SQlite should come with "?mode=rwc" to create the DB
## if not present.
## Example URLs:
##  - "postgres://postgres-user:password@postgres-server/my-database"
##  - "mysql://mysql-user:password@mysql-server/my-database"
##
## This can be overridden with the LLDAP_DATABASE_URL env variable.
database_url = "sqlite:///data/users.db?mode=rwc"

## Private key file.
## Contains the secret private key used to store the passwords safely.
## Note that even with a database dump and the private key, an attacker
## would still have to perform an (expensive) brute force attack to find
## each password.
## Randomly generated on first run if it doesn't exist.
## Alternatively, you can use key_seed to override this instead of relying on
## a file.
## Env variable: LLDAP_KEY_FILE
key_file = "/data/private_key"

## Seed to generate the server private key, see key_file above.
## This can be any random string, the recommendation is that it's at least 12
## characters long.
## Env variable: LLDAP_KEY_SEED
#key_seed = "RanD0m STR1ng"

## Ignored attributes.
## Some services will request attributes that are not present in LLDAP. When it
## is the case, LLDAP will warn about the attribute being unknown. If you want
## to ignore the attribute and the service works without, you can add it to this
## list to silence the warning.
#ignored_user_attributes = [ "sAMAccountName" ]
#ignored_group_attributes = [ "mail", "userPrincipalName" ]

## Options to configure SMTP parameters, to send password reset emails.
## To set these options from environment variables, use the following format
## (example with "password"): LLDAP_SMTP_OPTIONS__PASSWORD
[smtp_options]
## Whether to enabled password reset via email, from LLDAP.
enable_password_reset=true
## The SMTP server.
server="smtp.gmail.com"
## The SMTP port.
port=465
## How the connection is encrypted, either "NONE" (no encryption), "TLS" or "STARTTLS".
smtp_encryption = "NONE"
## The SMTP user, usually your email address.
user="<email>@gmail.com"
## The SMTP password.
password="<password>"
## The header field, optional: how the sender appears in the email. The first
## is a free-form name, followed by an email between <>.
from="LLDAP Admin <no-reply@example.com>"
## Same for reply-to, optional.
#reply_to="Do not reply <noreply@localhost>"

## Options to configure LDAPS.
## To set these options from environment variables, use the following format
## (example with "port"): LLDAP_LDAPS_OPTIONS__PORT
[ldaps_options]
## Whether to enable LDAPS.
#enabled=true
## Port on which to listen.
#port=6360
## Certificate file.
#cert_file="/data/cert.pem"
## Certificate key file.
#key_file="/data/key.pem"
```

I have added the `key_file` and mount the volume as shown o the compose file above. Is there something i missed?
