### ISSUE TITLE
[BUG] LLDAP_ADMIN_USERNAME should bootstrap admin username

### ISSUE THREAD

**Issue by cskwrd** [lldap/lldap#804]
**Describe the bug**
LLDAP_ADMIN_USERNAME should set the initial user's username if zero users exist. It is always set to admin.

**To Reproduce**
Spin up v0.5.0 container with the env var `LLDAP_ADMIN_USERNAME` set to anything but `admin`

**Expected behavior**
The initial user's username is the value of `LLDAP_ADMIN_USERNAME`

**Logs**
The ArgoCD bootstrap job outlined in the docs will fail if `LLDAP_ADMIN_USERNAME` is not `admin` on container creation

**Additional context**
- I am using k8s.
- My goal is to avoid any sort of default user that could be used in an automated attack. For me this means, no username of `admin`.

**Comment by martadinata666** [comment]
As the script contributed the user this maybe oversight.
This is a simple docker compose yaml to deploy custom admin user.
```
version: "3"
services:
  lldap:
    image: nitnelave/lldap:latest
    ports:
      - 3890:3890
      - 17170:17170
    environment:
      - LLDAP_LDAP_USER_DN=customadmin
      - LLDAP_JWT_SECRET=randomwords
      - LLDAP_LDAP_USER_PASS=adminadmin
      - LLDAP_LDAP_BASE_DN=dc=example,dc=com
      - LLDAP_VERBOSE=true
```
