### ISSUE TITLE
[BUG] No restrictions on sending "Forgot Password" emails, which may pose a security risk

### ISSUE THREAD

**Issue by Insulinocytus** [lldap/lldap#965]
**Describe the bug**

I tested sending multiple password reset emails to myself, and there were no warnings or limitations triggered, even after sending over a dozen emails.

Since my SMTP service charges per email, a hacker could easily guess my username (e.g., "admin") and send unlimited emails, potentially leading to significant costs for me.

Are there any plans to add CAPTCHA support to prevent such abuse?

I am not a web engineer myself, so any guidance or suggestions on how to address this issue would be greatly appreciated.

**To Reproduce**
Just send password reset email.

**Expected behavior**
You could consider setting a fixed interval, such as 1 minute, between sending emails to the same ID. Alternatively, requiring CAPTCHA verification before each email is sent could be another effective solution.

**Logs**
null

**Additional context**
null

**Comment by nitnelave** [comment]
This is such a common problem with services that I feel that it would be a shame if everyone implemented it independently, and badly. 

I feel like it would be better achieved through a local SMTP proxy with rate limiting.

**Comment by Insulinocytus** [comment]
> This is such a common problem with services that I feel that it would be a shame if everyone implemented it independently, and badly.

Agree.

> I feel like it would be better achieved through a local SMTP proxy with rate limiting.

Perhaps I can solve this by modifying my reverse proxy settings.

Anyway, thanks for your reply.

**Comment by nitnelave** [comment]
Yeah, you can either do that by applying limits to the incoming HTTP queries (which is always good if you're afraid of DDoS), or by applying limits on the outgoing SMTP by using an SMTP proxy before forwarding to your actual provider.

**Comment by Insulinocytus** [comment]
I'm using Traefik as a reverse proxy. Here's my solution.
In this way, each IP can only reset the password once every 30 seconds.

```yaml
# dynamic.yml

http:
  middlewares:
    lldapForgetPasswordMailRateLimit:
      ratelimit:
        average: 1
        period: 30s
        sourceCriterion:
          ipstrategy:
            excludedIPs:
              - 10.0.0.0/8
              - 172.16.0.0/12
              - 192.168.0.0/16
  routers:
    lldap:
      rule: Host(`lldap.your.site`)
      entryPoints: websecure
      service: lldap
      priority: 1
    lldap-forget-password-mail-request:
      rule: Host(`lldap.your.site`) && PathRegexp(`^/auth/reset/step1/.+$`)
      entryPoints: websecure
      service: lldap
      middlewares: lldapForgetPasswordMailRateLimit
      priority: 2
    lldap-forget-password-mail-request-exclud:
      rule: Host(`lldap.your.site`) && Path(`/auth/reset/step1/lldap_unlikely_very_long_user_name`)
      entryPoints: websecure
      service: lldap
      priority: 3
```

![image](https://github.com/user-attachments/assets/8c6fd9c9-605b-4142-9ece-766e7639a006)
